name: Authorization API
on: [push]

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.13
      - name: Install dependencies
        run: make install
      - name: Test with pytest
        run: make tests
      - name: Format code
        run: make format
      - name: Run Tests
        run: make tests

  push_to_docker_hub:
    runs-on: ubuntu-latest
    needs: testing
    steps:
      - uses: actions/checkout@v2
      
      - name: Push to Docker Hub
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        run: |
          docker build -t gave44362/myapp .
          docker tag gave44362/myapp:latest docker.io/gave44362/myapp:latest
          docker push docker.io/gave44362/myapp:latest
